### ISSUE TITLE
Clark/Fortran questions

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#1]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

I read in the README (& paper) "Implementation of the framework for hydrological modelling FUSE described in Clark et al. (2008) and based on the Fortran code provided by M. Clark in 2011. "

I'm absolutely not a licensing expert, so I just wonder whether the original Fortran code was released (and if so under which license -- but I guess it wasn't released since you mention it was kindly provided?), whether the author agreed to its use for a R package with the license you've chosen? Or maybe it doesn't play a role since your code is not a binding but rather a translation (and even improvement?) of the original code? Had you considered adding him as a contributor of the package? But I see DESCRIPTION too mention the original paper so this issue is probably useless. :-)

**Comment by cvitolo** [comment]
You made very good points here! The answers to your questions are certainly not obvious. 

In 2011, the author of fuse (Fortran) just provided the code to interested researchers and groups. I contacted Martyn and asked him if I could add his name as contributor to my re-implementation of fuse in R (JOSS paper) and he said that was not necessary. But he put me in contact with his postdoc who has recently taken over the fuse (fortran) code and released it under a GPL-3 license here: https://github.com/naddor/fuse. Our intention, in the future, is to merge our efforts and make a unique code with Rinterface but we haven't worked out the details yet. Any suggestion is welcome!

**Comment by maelle** [comment]
At least out a link to the Fortran implementation then?

If Fortran isn't used a lot, maybe this postdoc can come help you with the boring issues I've opened 😀

**Comment by cvitolo** [comment]
The github link above relates to the new version of fuse, not the one I originally worked on. 
Do you think that would confuse users?

**Comment by maelle** [comment]
Ah yes it might... maybe at the bottom of the README it could make sense to say something like "For Fortran users, please refer to the new version of fuse"? 

What differences are there between the old and the new version? It could make sense to mention that you plan to incorporate all new features of Fortran fuse in your R fuse and that the development of Fortran fuse might even stop in favor of R fuse?

**Comment by cvitolo** [comment]
I have added a link to the latest fortran fuse in the readme but I don't remember exactly what the new features are so I did not mention that. Also, the plan is to keep the fortran code and adapt my package to become the r interface to the fortran code. But I have no idea when that is going to happen...I'll add future plans to the README when I have a better idea ;)

**Comment by cvitolo** [comment]
@masalmon Are you ok if I close this issue?

**Comment by maelle** [comment]
Yes! Even doing it myself 😀
