### ISSUE TITLE
fuse

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#12]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

I wonder if the name of the function `fuse` is too confusing. Maybe you could rename it to something with "simulation" or "sim" in the name?

**Comment by maelle** [comment]
By the way are the two modules composing the functions used on their own a lot? If not, I'd only export the "meta-function".

**Comment by cvitolo** [comment]
The names of the functions are designed to be consistent with the naming convention adopted in hydromad and other hydrological models (e.g. topmodel).

fusesma.sim and fuserouting.sim can be used on their own, depending on the local catchment under study (e.g. area of the catchment, slope, etc).
