### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#13]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

Looking at codecov.io, it seems that the test coverage could be improved with a few more tests. :-)

**Comment by cvitolo** [comment]
You right, I have added all the necessary tests.

**Comment by maelle** [comment]
Ok, great, I see the tests, but I don't understand why the coverage as indicated [here](https://codecov.io/github/cvitolo/fuse?branch=master) doesn't seem to have changed? If you run covr locally, it must be a bit higher, right?

**Comment by cvitolo** [comment]
Yes, that's weird. I don't know why that happens. If I run covr locally I get a slightly higher percentage: ~63.46%. I guess it considers also the source code in the src folder....
