### ISSUE TITLE
One test is failing

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#16]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

I actually get an error now when running the tests, 
```
1. Failure: Ensemble run (@test-fuse.R#54) -------------------------------------
all(discharges == y) not equal to TRUE.
1 element mismatch

```

**Comment by maelle** [comment]
Hmm, now it doesn't fail, installation was probably the issue, sorry!

**Comment by cvitolo** [comment]
I'm glad it is not failing! phewwww
