### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#2]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

The README states `install.packages(c("DBI", "assertthat", "magrittr", "tibble", "maptree", "tgp", "zoo", "qualV"))`

But from DESCRIPTION the dependencies are
Imports: dplyr, zoo, tgp, stats
LinkingTo: BH, Rcpp
Suggests: testthat

Should the installation instructions be updated?

That said, I had no issue installing the package and am now running R CHECK 🎉

**Comment by maelle** [comment]
The installation instructions are in the vignette too, and also have a different list of dependencies.

**Comment by cvitolo** [comment]
Thanks for spotting this. The list of dependencies are now consistent across README, DESCRIPTION and vignette.

**Comment by maelle** [comment]
Awesome!
