### ISSUE TITLE
The plots don't appear in the README

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#3]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

A cache issue?

**Comment by cvitolo** [comment]
Thanks for spotting this! I had set the code chunck that generates the plot with eval = FALSE... which did not evaluate the code and therefore did not plot the figure. This is now sorted!

I also simplified the readme (according to ggplot2 [here](https://github.com/tidyverse/ggplot2)) and left all the examples in the vignette. This reduces redundancies considerably.

**Comment by maelle** [comment]
@cvitolo great! Maybe you could generate a website for the package with `pkgdown` to make it easier to browse the vignette then?

**Comment by maelle** [comment]
I don't know if you've used `pkgdown` before, I use it [here](https://github.com/ropensci/ropenaq) for instance.

**Comment by cvitolo** [comment]
never used `pkgdown` before, I'm going to have a look now.

**Comment by cvitolo** [comment]
I couldn't figure out how to generate a website using pkgdown from the vignette file, so I decided to opt for the easy option: generated the website using the settings->GitHub Pages.

Added a link to the title.

**Comment by maelle** [comment]
As you wish, but if you have any `pkgdown` question don't hesitate to ask. For ropenaq I think I only had to install pkgdown and then run:

```r
pkgdown::init()
pkgdown::build_site()
```

**Comment by maelle** [comment]
After that I had to change the settings to, to docs/, so that Github could use files in docs for the website. But clearly it doesn't matter to me how you produce your website, awesome that you now got one, maybe we can close this issue :-)

**Comment by cvitolo** [comment]
pkgdown is great! Just tried to build the website a is surprisingly simple. Thanks a lot for the tip!
