### ISSUE TITLE
Functions naming

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#7]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

This is only a suggestion: many exported functions of the package have a name starting with "fuse", why not all of them?

**Comment by cvitolo** [comment]
The functions that start with 'fuse' are part of the original modelling framework (translation from the Fortran code), those that do not start with fuse are extra utility functions I developed. I'd like to keep separate to remember which function is also available in the fortran code.
