### ISSUE TITLE
Name of and names in parameters

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#8]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

This is again only a suggestion and quite similar to the suggestions made for the other datasets so I should maybe have grouped them, sorry.

* parameters could have a more specific name, e.g. fuse_parameters.

* the column names could be even more explicit (but I don't know about usual hydrology abbreviation so maybe I'm wrong), e.g. `tishape` could be `topology_index_shape`

**Comment by maelle** [comment]
I guess if you change the names of the variables it'd mean also changing the name of the parameters of `fusesma.sim`, not fun but maybe user-friendlier?

**Comment by cvitolo** [comment]
The names of the parameters are the same as in the fortran code. I totally agree that they could be more explicit but, in the light of future developments using the latest fortran code, it is important I keep the same naming convention.
