### ISSUE TITLE
fuserouting.ranges and fusesma.ranges

### ISSUE THREAD

**Issue by maelle** [cvitolo/fuse#9]
This issue is part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/52)

The title of the doc of `fuserouting.ranges` is "Function to define the parameter ranges for GAMMA routing module" but the function has no parameter, it only returns the default parameters so it's not for defining something.

* I'd propose to change the title to "default parameter ranges" or something like that.

* maybe the name of the function could even contain the word "default"?

**Comment by maelle** [comment]
I have the same comments for `fusesma.ranges`.

**Comment by cvitolo** [comment]
The functions fuserouting.ranges and fusesma.ranges only exist to make fuse compatible with hydromad. It is a requirement of hydromad that the routing module is accompanied by a function defining the default parameter ranges (same for the sma module). The naming convention is also dictated by hydromad, therefore it cannot be changed...sorry!
